DROP DATABASE IF EXISTS SpringFoods;
CREATE DATABASE IF NOT EXISTS SpringFoods;
USE SpringFoods;

CREATE TABLE IF NOT EXISTS Apples (
  TREE_AGE INT,
  CATEGORY VARCHAR(100),
  COLOR VARCHAR(100),
  EXPIRATION DATE,
  ID INT NOT NULL PRIMARY KEY,
  POLLINATION_GROUP VARCHAR(100),
  PRODUCT VARCHAR(20),
  TREE_ID INT,
  VARIETY VARCHAR(20),
  SOLD BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Bananas (
  CATEGORY VARCHAR(100),
  EXPIRATION DATE,
  GENERATION INT,
  ID INT NOT NULL PRIMARY KEY,
  PRODUCT VARCHAR(20),
  TREE_ID INT ,
  VARIETY VARCHAR(20),
  SOLD BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Cows (
  VENDOR VARCHAR(20),
  ID INT NOT NULL PRIMARY KEY,
  LENGTH INT,
  WEIGHT INT
);

CREATE TABLE IF NOT EXISTS Milk (
  QUANTITY INT,
  CATEGORY VARCHAR(100),
  COW_ID INT,
  COW_AGE INT,
  COW_BREED VARCHAR(20),
  EXPIRATION DATE,
  VENDOR VARCHAR(100),
  AMOUNT_USED_SOLD INT DEFAULT 0,
  AMOUNT_REMAINING INT GENERATED ALWAYS AS (QUANTITY-AMOUNT_USED_SOLD)
);

CREATE TABLE IF NOT EXISTS Butters (
  QUANTITY INT,
  SOURCE_COW INT,
  CARTON_USED INT,
  CATEGORY VARCHAR(20),
  CHURNER VARCHAR(50),
  EXPIRATION DATE,
  AMOUNT_USED_SOLD INT DEFAULT 0,
  AMOUNT_REMAINING INT GENERATED ALWAYS AS (QUANTITY-AMOUNT_USED_SOLD)
);

CREATE TABLE IF NOT EXISTS Transactions (
  PRICE DECIMAL(10,2),
  SOLD_TO VARCHAR(100),
  ITEM_ID VARCHAR(100) NOT NULL PRIMARY KEY
);
