LOAD DATA
  LOCAL
  INFILE '/Users/woo/Desktop/Spring-Foods/files/orders/Heritage Farms/2018-11-12/Samples.csv' 
  INTO TABLE Apples 
  FIELDS
    TERMINATED BY ',' 
    OPTIONALLY ENCLOSED BY '"'
  LINES
    TERMINATED BY '\n'
  IGNORE 1 LINES
  (@TREE_AGE, CATEGORY, COLOR, EXPIRATION, ID, POLLINATION_GROUP, PRODUCT, TREE_ID, VARIETY)
  SET TREE_AGE = CAST(SUBSTRING(@TREE_AGE, 0, 2) AS INT);